// <auto-generated />
namespace CostMateAngular.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AfterAddingIsAdmintoAppUserandViewCounttoMateItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterAddingIsAdmintoAppUserandViewCounttoMateItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131545529_After Adding IsAdmin to AppUser and ViewCount to MateItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
