// <auto-generated />
namespace CostMateAngular.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AfteraddingApprovedandShowOnHomePagetoMateItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfteraddingApprovedandShowOnHomePagetoMateItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131326474_After adding Approved and ShowOnHomePage to MateItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
